---
# tasks file for nginx
- name: Installer Nginx sur le node
  hosts: node
  become: yes
  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes

    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer et activer Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Installer curl
      apt:
        name: curl
        state: present

    - name: Verifier url
      uri:
        url: http://localhost
        status_code: 200
